--1
SELECT P.ID, P. NOMBRE, P.APELLIDO1, P.APELLIDO2, ASI.CODIGO, ASI.NOMBRE
FROM PROFESORES P JOIN IMPARTIR I ON (P.ID=I.PROFESOR) JOIN ASIGNATURAS ASI ON (I.ASIGNATURA = ASI.CODIGO);
--sol
select * from sol_2_5;

--2
SELECT P.NOMBRE , P.APELLIDO1, P.APELLIDO2,NVL(P.DIRECTOR_TESIS,'NO TIENE')
FROM PROFESORES P;
--sol
select * from sol_5_2;

--3
SELECT P1.NOMBRE, P1.APELLIDO1, NVL(P1.APELLIDO2,' '), TRUNC(months_between(SYSDATE, P1.ANTIGUEDAD)/12) AS ANTIGUEDAD, P2.NOMBRE, P2.APELLIDO1, NVL(P2.APELLIDO2, ' '), TRUNC(months_between(SYSDATE, P2.ANTIGUEDAD)/12) AS ANTIGUEDAD
FROM  PROFESORES P1, PROFESORES P2
WHERE ABS(TRUNC(months_between(P1.ANTIGUEDAD, P2.ANTIGUEDAD)/12))<2  AND P1.DEPARTAMENTO=P2.DEPARTAMENTO AND P1.ID<P2.ID;
--SOL
select * from sol_2_8;

--4
SELECT A1.NOMBRE, A2.NOMBRE, A3.NOMBRE, A1.COD_MATERIA
FROM ASIGNATURAS A1, ASIGNATURAS A2 , ASIGNATURAS A3 
WHERE A1.COD_MATERIA = A2.COD_MATERIA AND A2.COD_MATERIA = A3.COD_MATERIA AND A1.CODIGO<A2.CODIGO AND A2.CODIGO<A3.CODIGO;
--SOL
select * from sol_2_10;

--5
SELECT A.NOMBRE,A.APELLIDO1, NVL(A.APELLIDO2,' ')
FROM ALUMNOS A JOIN MATRICULAR M ON(A.DNI=M.ALUMNO) JOIN ASIGNATURAS ASI ON (M.ASIGNATURA=ASI.CODIGO) JOIN IMPARTIR I ON(ASI.CODIGO = I.ASIGNATURA) JOIN PROFESORES P ON(I.PROFESOR=P.ID)
WHERE UPPER(P.NOMBRE||' ' ||P.APELLIDO1) = 'ENRIQUE SOLER' AND I.CURSO = M.CURSO AND I.GRUPO = M.GRUPO ORDER BY A.APELLIDO1,A.APELLIDO2,A.NOMBRE;
--SOL
select * from sol_2_12;

--6
SELECT ASI.NOMBRE AS ASIGNATURA, M.NOMBRE AS MATERIA, P. NOMBRE || ' ' || P.APELLIDO1 ||' '|| NVL(P.APELLIDO2,' ') AS PROFESOR, I.CARGA_CREDITOS
FROM MATERIAS M JOIN ASIGNATURAS ASI ON(M.CODIGO=ASI.COD_MATERIA) JOIN IMPARTIR I ON(ASI.CODIGO=I.ASIGNATURA) JOIN PROFESORES P ON(I.PROFESOR=P.ID)
WHERE I.CARGA_CREDITOS IS NOT NULL ORDER BY M.CODIGO, ASI.NOMBRE DESC;
--SOL
select * from sol_2_14;

--7
SELECT ASI.NOMBRE AS ASIGNATURA, D.NOMBRE AS DEPARTAMENTO , ASI.CREDITOS, ROUND((NVL(ASI.PRACTICOS, '0')/ASI.CREDITOS)*100,2) AS CRED_PRAC
FROM ASIGNATURAS ASI JOIN DEPARTAMENTOS D ON(ASI.DEPARTAMENTO=D.CODIGO)
WHERE ASI.CREDITOS IS NOT NULL AND ASI.PRACTICOS IS NOT NULL ORDER BY CRED_PRAC DESC;
--SOL
select * from sol_2_15;

--8
SELECT A.APELLIDO1
FROM ALUMNOS A 
WHERE UPPER(A.APELLIDO1) LIKE '%LL%'

UNION

SELECT A.APELLIDO2
FROM ALUMNOS A 
WHERE  UPPER(A.APELLIDO2) LIKE '%LL%'

UNION

SELECT P.APELLIDO1
FROM PROFESORES P
WHERE UPPER(P.APELLIDO1) LIKE '%LL%'

UNION

SELECT P.APELLIDO2
FROM PROFESORES P
WHERE UPPER(P.APELLIDO2) LIKE '%LL%' ORDER BY 1;

--sol
select * from sol_2_19;

--9
SELECT 'El director de' ||' '|| P.NOMBRE ||' '|| P.APELLIDO1||' '||P.APELLIDO2 ||' '|| 'ES' || S.NOMBRE ||' '||S.APELLIDO1||' '||S.APELLIDO2 AS TESIS, NVL(I.TRAMOS,'0') AS TRAMOS
FROM PROFESORES S LEFT OUTER JOIN INVESTIGADORES I ON(I.ID_PROFESOR=S.ID) JOIN PROFESORES P ON(S.ID=P.DIRECTOR_TESIS)
WHERE P.DIRECTOR_TESIS IS NOT NULL;
--SOL
select * from sol_2_23;

--10
SELECT A1.NOMBRE,A1.APELLIDO1,A2.APELLIDO2,A2.NOMBRE AS NOMBRE2,A2.APELLIDO1 AS APELLIDO2_1,A2.APELLIDO2 AS APELLIDO2_2
FROM ALUMNOS A1 LEFT OUTER JOIN ALUMNOS A2 ON (A1.FECHA_PRIM_MATRICULA = A2.FECHA_PRIM_MATRICULA AND A1.DNI < A2.DNI)
ORDER BY 2,1;
--SOL
select * from sol_2_24;
