--1
SELECT I.ASIGNATURA
FROM IMPARTIR I
WHERE I.PROFESOR IN
(SELECT P.ID
FROM PROFESORES P
WHERE UPPER(P.NOMBRE ||' '|| P.APELLIDO1) = 'MANUEL ENCISO') ;

--SOL
select * from sol_6_1;

--2
SELECT M.ALUMNO
FROM MATRICULAR M JOIN ASIGNATURAS ASI ON(ASI.CODIGO=M.ASIGNATURA)
WHERE  (M.ASIGNATURA, M.GRUPO, M.CURSO) IN
(SELECT I.ASIGNATURA, I.GRUPO, I.CURSO
FROM IMPARTIR I
WHERE I.PROFESOR= 'C-34-TU-00');
--SOL
select * from docencia.sol_6_2;

--aux

--3
SELECT D.NOMBRE AS DEPARTAMENTO, SUM(ASI.CREDITOS) AS CREDITOS
FROM ASIGNATURAS ASI JOIN DEPARTAMENTOS D ON(ASI.DEPARTAMENTO=D.CODIGO)
GROUP BY D.NOMBRE
ORDER BY CREDITOS DESC;

--SOL
select * from sol_3_2;

--4
SELECT P.DESPACHO, SUM(I.CARGA_CREDITOS) AS CREDITOS
FROM PROFESORES P JOIN IMPARTIR I ON(P.ID=I.PROFESOR)
WHERE P.DESPACHO IS NOT NULL
GROUP BY P.DESPACHO;
--SOL
select * from sol_3_4;

--5
SELECT DISTINCT M.ALUMNO, M.ASIGNATURA, ASI1.NOMBRE
FROM ASIGNATURAS ASI1 JOIN MATRICULAR M ON (ASI1.CODIGO=M.ASIGNATURA) 
WHERE(M.ALUMNO ,ASI1.CREDITOS) IN (SELECT M1.ALUMNO, MAX(ASI2.CREDITOS)
                     FROM MATRICULAR M1 JOIN ASIGNATURAS ASI2 ON (ASI2.CODIGO=M1.ASIGNATURA)
                     GROUP BY M1.ALUMNO) ORDER BY M.ALUMNO;
                     
                     

--SOL
select * from sol_3_8;

--6
SELECT D.NOMBRE AS DEPARTAMENTO , ASI.NOMBRE AS ASIGNATURA
FROM DEPARTAMENTOS D JOIN ASIGNATURAS ASI ON (ASI.DEPARTAMENTO=D.CODIGO) 
WHERE(D.CODIGO ,ASI.CREDITOS) IN (SELECT D.CODIGO, MIN(ASI.CREDITOS)
                     FROM DEPARTAMENTOS D JOIN ASIGNATURAS ASI ON (ASI.DEPARTAMENTO=D.CODIGO)
                     GROUP BY D.CODIGO);
--SOL
select * from sol_3_10;

--7
SELECT D.NOMBRE
FROM DEPARTAMENTOS D JOIN ASIGNATURAS ASI ON(ASI.DEPARTAMENTO=D.CODIGO)
GROUP BY D.NOMBRE
HAVING COUNT(*) =(SELECT MAX(COUNT(*))
        FROM DEPARTAMENTOS D JOIN ASIGNATURAS ASI ON(ASI.DEPARTAMENTO=D.CODIGO)
        GROUP BY D.CODIGO);

--SOL
select * from sol_3_13;

--8
SELECT P.NOMBRE, P.APELLIDO1, P.APELLIDO2
FROM PROFESORES P JOIN IMPARTIR I ON (I.PROFESOR=P.ID)
GROUP BY P.NOMBRE,P.APELLIDO1,P.APELLIDO2,  I.PROFESOR
HAVING SUM(I.CARGA_CREDITOS) > (SELECT AVG(SUM(CARGA_CREDITOS)) FROM IMPARTIR GROUP BY PROFESOR );

--SOL
select * from sol_3_15;

--9
SELECT D.NOMBRE
FROM DEPARTAMENTOS D 
WHERE D.CODIGO NOT IN (SELECT ASI.DEPARTAMENTO
                         FROM ASIGNATURAS ASI 
                         WHERE ASI.CREDITOS > 6);

--SOL
select * from sol_3_18;

--10
SELECT P1.NOMBRE ||' '||P1.APELLIDO1||' '|| P1.APELLIDO2 AS PROFESOR_1,P2.NOMBRE||' '||P2.APELLIDO1||' '||P2.APELLIDO2 AS PROFESOR_2
FROM PROFESORES P1 ,PROFESORES P2
WHERE P1.ID<P2.ID AND (P1.ID,P2.ID) NOT IN
(SELECT I1.PROFESOR,I2.PROFESOR
FROM IMPARTIR I1,IMPARTIR I2,MATRICULAR M,MATRICULAR M1
WHERE I1.GRUPO=M.GRUPO AND I1.CURSO= M.CURSO AND I1.ASIGNATURA=M.ASIGNATURA 
AND I2.GRUPO=M1.GRUPO AND I2.CURSO= M1.CURSO AND I2.ASIGNATURA=M1.ASIGNATURA 
AND I1.PROFESOR<I2.PROFESOR AND M.ALUMNO = M1.ALUMNO);

--SOL
select * from sol_3_20;
